name: Bohema
favicon: null
layout_spectrum: 0.73118
typography_spectrum: 0.81076
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191b18'
    - '#5c837e'
    - '#3a4740'
    - '#a7e6d7'
    - '#f8fcf6'
  brandStrength: 0.34270980791188776
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
